CREATE DATABASE QLDA
GO
USE QLDA
GO

-- CREATE TABLES
CREATE TABLE DEAN
(
	TENDA NVARCHAR(50),
	MADA INT NOT NULL,
	DDIEM_DA NVARCHAR(20) NOT NULL,
	PRIMARY KEY (MADA)
)

CREATE TABLE PHONGBAN
(
	TENPHG NVARCHAR(20),
	MAPHG INT NOT NULL,
	PRIMARY KEY (MAPHG)
)

CREATE TABLE NHANVIEN
(
	HONV NVARCHAR(15),
	TENLOT NVARCHAR(15),
	TENNV NVARCHAR(15),
	MANV NVARCHAR(9) NOT NULL,
	NGSINH smalldatetime,
	DCHI NVARCHAR(30),
	PHAI NVARCHAR(3),
	LUONG FLOAT,
	PHG INT NOT NULL,
	
	PRIMARY KEY (MANV)
)

CREATE TABLE THANNHAN
(
	MA_NVIEN NVARCHAR(9) NOT NULL,
	TENTN NVARCHAR(15),
	PHAI NVARCHAR(3),
	NGSINH smallDATEtime,
	QUANHE NVARCHAR(15),
	
	PRIMARY KEY (MA_NVIEN, TENTN)
)

CREATE TABLE PHANCONG
(
	MA_NVIEN NVARCHAR(9) NOT NULL,
	MADA INT NOT NULL,
	THOIGIAN FLOAT,
	
	PRIMARY KEY (MA_NVIEN, MADA)
)

-- Cài đặt ràng buộc khóa ngoại cho các bảng 
ALTER TABLE DEAN
ADD CONSTRAINT FK_DEAN_PHONG
FOREIGN KEY (PHONG)
REFERENCES PHONGBAN (MAPHG)

ALTER TABLE NHANVIEN
ADD CONSTRAINT FK_NHANVIEN_PHONGBAN
FOREIGN KEY (PHG)
REFERENCES PHONGBAN (MAPHG)

ALTER TABLE PHANCONG
ADD CONSTRAINT FK_PHANCONG_DEAN
FOREIGN KEY (MADA)
REFERENCES DEAN (MADA)

ALTER TABLE PHANCONG
ADD CONSTRAINT FK_PHANCONG_NHANVIEN
FOREIGN KEY (MA_NVIEN)
REFERENCES NHANVIEN (MANV)

ALTER TABLE THANNHAN
ADD CONSTRAINT FK_THANNHAN_NHANVIEN
FOREIGN KEY (MA_NVIEN)
REFERENCES NHANVIEN (MANV)

BEGIN /** NHANVIEN **/
	ALTER TABLE NHANVIEN
	NOCHECK CONSTRAINT ALL
	INSERT INTO NHANVIEN (HONV, TENLOT, TENNV, MANV, NGSINH, DCHI, PHAI, LUONG, PHG)
	VALUES (N'Đinh', N'Bá', N'Tiến', '123', '02/27/1982', N'Mộ Đức', N'Nam', 30000, 4)
	INSERT INTO NHANVIEN (HONV, TENLOT, TENNV, MANV, NGSINH, DCHI, PHAI, LUONG, PHG)
	VALUES (N'Nguyễn', N'Thanh', N'Tùng', '234', '08/12/1956', N'Sơn Tịnh', N'Nam', 40000, 5)
	INSERT INTO NHANVIEN (HONV, TENLOT, TENNV, MANV, NGSINH, DCHI, PHAI, LUONG, PHG)
	VALUES (N'Bùi', N'Thúy', N'Vũ', '345', '03/11/1954', N'Tư Nghĩa', N'Nữ', 25000,  4)
	INSERT INTO NHANVIEN (HONV, TENLOT, TENNV, MANV, NGSINH, DCHI, PHAI, LUONG, PHG)
	VALUES (N'Lê', N'Thị', N'Nhàn', '456', '07/12/1962', N'Mộ Đức', N'Nữ', 43000,  4)
	INSERT INTO NHANVIEN (HONV, TENLOT, TENNV, MANV, NGSINH, DCHI, PHAI, LUONG, PHG)
	VALUES (N'Nguyễn', N'Mạnh', N'Hùng', '567', '03/25/1985', N'Sơn Tịnh', N'Nam', 38000,  5)
	INSERT INTO NHANVIEN (HONV, TENLOT, TENNV, MANV, NGSINH, DCHI, PHAI, LUONG, PHG)
	VALUES (N'Trần', N'Thanh', N'Tâm', '789', '06/17/1972', N'Tp.Quãng Ngãi', N'Nam', 25000,  5)
	INSERT INTO NHANVIEN (HONV, TENLOT, TENNV, MANV, NGSINH, DCHI, PHAI, LUONG, PHG)
	VALUES (N'Trần', N'Hồng', N'Quang', '678', '09/01/1967', N'Bình Sơn', N'Nam', 25000,  5)
	INSERT INTO NHANVIEN (HONV, TENLOT, TENNV, MANV, NGSINH, DCHI, PHAI, LUONG, PHG)
	VALUES (N'Cao', N'Thanh', N'Huyền', '890', '01/01/1965', N'Tư Nghĩa', N'Nữ', 55000, 1)
	INSERT INTO NHANVIEN (HONV, TENLOT, TENNV, MANV, NGSINH, DCHI, PHAI, LUONG, PHG)
	VALUES (N'Vương', N'Ngọc', N'Quyền', '901', '12/12/1987', N'Mộ Đức', N'Nam', 30000, 1)
	ALTER TABLE NHANVIEN
	CHECK CONSTRAINT ALL
END

BEGIN /** PHONGBAN **/
	ALTER TABLE PHONGBAN
	NOCHECK CONSTRAINT ALL
	INSERT INTO PHONGBAN (TENPHG, MAPHG)
	VALUES (N'Nghiên cứu', 5)
	INSERT INTO PHONGBAN (TENPHG, MAPHG)
	VALUES (N'Điều hành', 4)
	INSERT INTO PHONGBAN (TENPHG, MAPHG)
	VALUES (N'Quản lý', 1)
	ALTER TABLE PHONGBAN
	CHECK CONSTRAINT ALL
END

BEGIN /** DEAN **/
	ALTER TABLE DEAN
	NOCHECK CONSTRAINT ALL
	INSERT INTO DEAN (TENDA, MADA, DDIEM_DA)
	VALUES (N'Nâng cao chất lượng muối', 1, N'Sa Huỳnh')
	INSERT INTO DEAN (TENDA, MADA, DDIEM_DA)
	VALUES (N'Xây dựng nhà máy chế biến thủy sản', 10, N'Dung Quất')
	INSERT INTO DEAN (TENDA, MADA, DDIEM_DA)
	VALUES (N'Phát triển hạ tầng mạng', 2, N'Tp. Quảng Ngãi')
	INSERT INTO DEAN (TENDA, MADA, DDIEM_DA)
	VALUES (N'Truyền tải cáp quang', 20, N'Tp. Quảng Ngãi')
	INSERT INTO DEAN (TENDA, MADA, DDIEM_DA)
	VALUES (N'Tin học hóa trường học', 3, N'Ba tơ')
	INSERT INTO DEAN (TENDA, MADA, DDIEM_DA)
	VALUES (N'Đào tạo nhân lực', 30, N'Tịnh Phong')
	ALTER TABLE DEAN
	CHECK CONSTRAINT ALL
END

BEGIN /** THANNHAN **/
	ALTER TABLE THANNHAN
	NOCHECK CONSTRAINT ALL
	INSERT INTO THANNHAN (MA_NVIEN, TENTN, PHAI, NGSINH, QUANHE)
	VALUES ('123', N'Châu', N'Nữ', '10/30/2005', N'Con gái')
	INSERT INTO THANNHAN (MA_NVIEN, TENTN, PHAI, NGSINH, QUANHE)
	VALUES ('123', N'Duy', N'Nam', '10/25/2001', N'Con trai')
	INSERT INTO THANNHAN (MA_NVIEN, TENTN, PHAI, NGSINH, QUANHE)
	VALUES ('123', N'Phương', N'Nữ', '10/30/1985', N'Vợ chồng')
	INSERT INTO THANNHAN (MA_NVIEN, TENTN, PHAI, NGSINH, QUANHE)
	VALUES ('234', N'Thanh', N'Nữ', '04/05/1980', N'Con gái')
	INSERT INTO THANNHAN (MA_NVIEN, TENTN, PHAI, NGSINH, QUANHE)
	VALUES ('345', N'Dương', N'Nam', '10/30/1956', N'Vợ chồng')
	INSERT INTO THANNHAN (MA_NVIEN, TENTN, PHAI, NGSINH, QUANHE)
	VALUES ('345', N'Khang', N'Nam', '10/25/1982', N'Con trai')
	INSERT INTO THANNHAN (MA_NVIEN, TENTN, PHAI, NGSINH, QUANHE)
	VALUES ('456', N'Hùng', N'Nam', '01/01/1987', N'Con trai')
	INSERT INTO THANNHAN (MA_NVIEN, TENTN, PHAI, NGSINH, QUANHE)
	VALUES ('901', N'Thương', N'Nữ', '04/05/1989', N'Vợ chồng')
	ALTER TABLE THANNHAN
	CHECK CONSTRAINT ALL
END

BEGIN /** PHANCONG **/
	ALTER TABLE PHANCONG
	NOCHECK CONSTRAINT ALL
	INSERT INTO PHANCONG (MA_NVIEN, MADA, THOIGIAN)
	VALUES ('123', 1, 33)
	INSERT INTO PHANCONG (MA_NVIEN, MADA, THOIGIAN)
	VALUES ('123', 2, 8)
	INSERT INTO PHANCONG (MA_NVIEN, MADA, THOIGIAN)
	VALUES ('345', 10, 10)
	INSERT INTO PHANCONG (MA_NVIEN, MADA, THOIGIAN)
	VALUES ('345', 20, 10)
	INSERT INTO PHANCONG (MA_NVIEN, MADA, THOIGIAN)
	VALUES ('345', 3, 10)
	INSERT INTO PHANCONG (MA_NVIEN, MADA, THOIGIAN)
	VALUES ('456', 1, 20)
	INSERT INTO PHANCONG (MA_NVIEN, MADA, THOIGIAN)
	VALUES ('456', 2, 20)
	INSERT INTO PHANCONG (MA_NVIEN, MADA, THOIGIAN)
	VALUES ('678', 3, 40)
	INSERT INTO PHANCONG (MA_NVIEN, MADA, THOIGIAN)
	VALUES ('789', 10, 35)
	INSERT INTO PHANCONG (MA_NVIEN, MADA, THOIGIAN)
	VALUES ('789', 20, 30)
	INSERT INTO PHANCONG (MA_NVIEN, MADA, THOIGIAN)
	VALUES ('789', 30, 5)
	ALTER TABLE PHANCONG
	CHECK CONSTRAINT ALL
END
GO

BEGIN /** BÀI TẬP **/
--1. Liệt kê danh sách tất cả các nhân viên.
SELECT*
FROM NHANVIEN

--2. Tìm các nhân viên làm việc ở phòng số 5.
SELECT HONV + ' ' + TENLOT + ' ' + TENNV AS N'Nhân viên phòng 5'
FROM NHANVIEN
WHERE NHANVIEN.PHG = 5

--3. Liệt kê họ tên và phòng làm việc các nhân viên có mức lương trên 6.000.000 đồng.
SELECT HONV + ' ' + TENLOT + ' ' + TENNV AS 'Họ tên NV', TENPHG
FROM NHANVIEN, PHONGBAN 
where NHANVIEN.PHG = PHONGBAN.MAPHG and (NHANVIEN.LUONG > '50000')

--4. Tìm các nhân viên có mức lương trên 6.500.000 ở phòng 1 hoặc các nhân viên có mức lương trên 5.000.000 ở phòng 4.
SELECT HONV + ' ' + TENLOT + ' ' + TENNV AS 'Họ tên NV', MANV, MAPHG
FROM NHANVIEN, PHONGBAN
WHERE NHANVIEN.PHG = PHONGBAN.MAPHG AND (NHANVIEN.LUONG > 65000 AND PHONGBAN.MAPHG = 1) OR (NHANVIEN.LUONG > 50000 AND PHONGBAN.MAPHG = 4)

--5. Cho biết họ tên đầy đủ của các nhân viên ở TP Quảng Ngãi.
SELECT HONV + ' ' + TENLOT + ' ' + TENNV AS N'Nhân viên'
FROM NHANVIEN
WHERE NHANVIEN.DCHI = 'Tp.Quãng Ngãi'

--6. Cho biết họ tên đầy đủ của các nhân viên có họ bắt đầu bằng ký tự 'N'.
SELECT HONV + ' ' + TENLOT + ' ' + TENNV AS N'Nhân viên'
FROM NHANVIEN
WHERE NHANVIEN.HONV like 'N%'

--7. Cho biết ngày sinh và địa chỉ của nhân viên Cao Thanh Huyền.
SELECT NGSINH, DCHI
FROM NHANVIEN
WHERE NHANVIEN.HONV = N'Cao' AND NHANVIEN.TENLOT = N'Thanh' AND NHANVIEN.TENNV = N'Huyền'

--8. Cho biết các nhân viên có năm sinh trong khoảng 1955 đến 1975.
SELECT HONV + ' ' + TENLOT + ' ' + TENNV AS N'Nhân viên'
FROM NHANVIEN
WHERE YEAR(NGSINH) BETWEEN 1955 AND 1975

--9. Cho biết các nhân viên và năm sinh của nhân viên.
SELECT MANV, YEAR(NGSINH) AS 'Năm sinh'
FROM NHANVIEN

--10. Cho biết họ tên và tuổi của tất cả các nhân viên.
SELECT HONV + ' ' + TENLOT + ' ' + TENNV AS N'Nhân viên', (YEAR(GETDATE()) - YEAR(NGSINH)) AS 'Tuổi'
FROM NHANVIEN

--11. Tìm tên những người trưởng phòng của từng phòng ban.

--12. Tìm tên và địa chỉ của tất cả các nhân viên của phòng 'Điều hành'.
SELECT HONV + ' ' + TENLOT + ' ' + TENNV AS N'Nhân viên', DCHI
FROM NHANVIEN, PHONGBAN
WHERE NHANVIEN.PHG = PHONGBAN.MAPHG AND PHONGBAN.TENPHG = N'Điều hành'

--13. Với mỗi đề án ở Tp Quảng Ngãi, cho biết tên đề án, tên phòng ban, họ tên và ngày nhận chức của trưởng phòng của phòng ban chủ trì đề án đó.
SELECT TENDA, TENPHG, HONV + ' ' + TENLOT + ' ' + TENNV AS N'Nhân viên'
FROM NHANVIEN, PHONGBAN, DEAN
WHERE PHONGBAN.MAPHG = NHANVIEN.PHG and DDIEM_DA like N'%Tp. Quảng Ngãi'

--14. Tìm tên những nữ nhân viên và tên người thân của họ.
SELECT (NHANVIEN.HONV + ' ' + NHANVIEN.TENLOT + ' ' + NHANVIEN.TENNV) AS 'Nhân viên', THANNHAN.TENTN
FROM NHANVIEN, THANNHAN
WHERE NHANVIEN.MANV = THANNHAN.MA_NVIEN AND NHANVIEN.PHAI = N'Nữ'

--15. Với mỗi nhân viên, cho biết họ tên của nhân viên, họ tên trưởng phòng của phòng ban mà nhân viên đó đang làm việc.
SELECT (NV.HONV + ' ' + NV.TENLOT + ' '+ NV.TENNV) AS 'Họ tên nhân viên', (TRG.HONV + ' ' + TRG.TENLOT + ' '+ TRG.TENNV) AS 'Họ tên Trưởng phòng'
FROM NHANVIEN AS NV, NHANVIEN AS TRG
WHERE TRG.MANV = NV.MA_NQL

--16. Tên những nhân viên phòng Nghiên cứu có tham gia vào đề án Xây dựng nhà máy chế biến thủy sản.
SELECT (NHANVIEN.HONV + ' ' + NHANVIEN.TENLOT + ' ' + NHANVIEN.TENNV) AS 'Họ tên nhân viên '
FROM NHANVIEN inner join DEAN on  NHANVIEN.PHG = DEAN.MADA 
Where NHANVIEN.PHG = 5 AND DEAN.TENDA = N'Xây dựng nhà máy chế biến thủy sản' 

--17.  Cho biết tên các đề án mà nhân viên Trần Thanh Tâm đã tham gia.
SELECT TENDA
FROM NHANVIEN, DEAN, PHANCONG
WHERE DEAN.MADA	= PHANCONG.MADA AND
		  NHANVIEN.MANV = PHANCONG.MA_NVIEN AND
		  NHANVIEN.HONV = N'Trần' AND
		  NHANVIEN.TENLOT = N'Thanh' AND
		  NHANVIEN.TENNV = N'Tâm'
END